version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: asd-firm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: asd_firm
      MYSQL_USER: asd_user
      MYSQL_PASSWORD: asd_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asd-firm-network

  redis:
    image: redis:7-alpine
    container_name: asd-firm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - asd-firm-network

  app:
    build: .
    container_name: asd-firm-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    volumes:
      - app_logs:/app/logs
    networks:
      - asd-firm-network

volumes:
  mysql_data:
  redis_data:
  app_logs:

networks:
  asd-firm-network:
    driver: bridge