spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asd_firm?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: 10000ms
          max-idle: 10
          min-idle: 5

jwt:
  secret: ${JWT_SECRET:asdFirmSecretKey2024ForJWTTokenGenerationAndValidation}
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8135
  servlet:
    context-path: /api

logging:
  level:
    com.example.end: info
    org.springframework.security: warn
    org.hibernate: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/application.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: true
    db:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:false}
